{
   "env": {
      "commonjs": true,
      "es6": true,
      "browser": true
   },
   "parser": "babel-eslint",
   "extends": "eslint:recommended",
   "globals": {
      "before": true,
      "describe": true,
      "it": true,
      "process": true,
      "expect": true,
      "__dirname": true,
      "__testBase": true

   },
   "parserOptions": {
      "ecmaVersion": 2017,
      "sourceType": "module"
   },
   "rules": {
      "linebreak-style": [
         "error",
         "unix"
      ],
      "semi": [
         "error",
         "always"
      ],
      "no-console": "off",
      "no-var": "warn",
      "prefer-const": "warn",
      "arrow-body-style": ["error", "as-needed"]
   }
}
