language: node_js
node_js:
  - 8.0.0
before_script:
  - npm install
script:
  - npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    local_dir: public
    email: $GITHUB_MAIL
  - provider: npm
    email: $GITHUB_MAIL
    skip_cleanup: true
    on:
      tags: true
      repo: weihanchen/elasticsearch-builder
      branch: master
      node: '8.0.0'

branches:
  only:
    - master
notification:
  email:
    - ${GITHUB_MAIL}
  on_success: always